

puts "The students of Makers Apprecticeship Academy"
puts "-------------"
puts "Bruce Wayne"
puts "Bruce Banner"
puts "Barry Allen"
puts "Iris West"
puts "Clark Kent"
puts "Dr. Who"
puts "Terminator"
puts "Nancy Drew"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"